### ISSUE TITLE
bug: comments from the recipe aren't displayed in the recipe section

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/Atlas#30]
In the custom image's recipe we have some comments added, and when checking its corresponding recipe section in Atlas at https://images.vanillaos.org/#/recipe/custom, the comments aren't displayed. Also, in some parts of the recipe, there are `&ref_0` and `*ref_0` patterns specified throughout the page (no idea how it is added).

## Reference image

Actual ->

```yml
  - name: example-modules # Sample module demonstrating importing local and remote modules
    type: includes
    includes:
      - modules/50-install-debs.yml # Sample local module present in this repository
      - gh:vanilla-os/dev-image:main:modules/00-basics.yml # Sample GitHub remote module in the format: `gh:your-name/your-repo:branch:modules/file.yml`
      - https://raw.githubusercontent.com/Vanilla-OS/dev-image/main/modules/05-go.yml # Sample full URL remote module
```

Rendered ->

![image](https://github.com/Vanilla-OS/Atlas/assets/26346867/e3bc7045-6205-428f-a859-03e650900e8b)
